name: Code Review
on:
  push:
    branches:
        - master

jobs:
    review:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                    node-version: 16

            - name: Install dependencies
              run: npm install
              id: install
              continue-on-error: true

            - name: Lint code
              run: npm run lint
              id: lint
              continue-on-error: true

            - name: Run tests
              run: npm test
              id: test
              continue-on-error: true

            - name: CodeQL analysis
              uses: github/codeql-action/init@v2
              with:
                  languages: JavaScript,TypeScript
              id: codeql-init
              continue-on-error: true

            - name: CodeQL analysis (run)
              uses: github/codeql-action/analyze@v2
              id: codeql-run
              continue-on-error: true

            - name: Summary
              run: |
                  echo "Install dependencies: ${{ steps.install.outcome }}"
                  echo "Lint code: ${{ steps.lint.outcome }}"
                  echo "Run tests: ${{ steps.test.outcome }}"
                  echo "CodeQL analysis (init): ${{ steps.codeql-init.outcome }}"
                  echo "CodeQL analysis (run): ${{ steps.codeql-run.outcome }}"