name: Dependency Updates

on:
  schedule:
    # Run monthly on the 1st day at 00:00 UTC
    - cron: '0 0 1 * *'
  push:
    branches:
      - master
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Fetch dependency update metadata
      id: fetch-metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}