name: Documentation Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npm run docs:build

      - name: Clean existing contents
        run: |
          rm -rf *  # Warning: This will remove all files in the current directory. Be cautious with this command.
          echo "Cleaned up existing files."

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_ACTIONS_REPO_ACCESS }}
          branch: master  # Ensure this is the branch you want to deploy to
          folder: ./docs
          clean: true  # Ensures the deployment folder is clean before deploying
          

      - name: Debugging deployment
        if: failure()  # This step runs if the previous steps fail
        run: |
          echo "Deployment failed with exit code ${{ steps.deploy.outcome }}"
          git status
          git log -1
