name: Scheduled Tasks

on:
  # schedule:
  #   # Run weekly on Sunday at 00:00 UTC
  #   - cron: '0 0 * * SUN'
  push:
    branches:
      - master

jobs:
  weekly-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Run weekly task
        run: ./scripts/scheduled-task.sh

      # - name: Send Mail Action
      #   id: sendmail
      #   uses: vineetchoudhary/mailgun-action@master
      #   with:
      #     api-key: ${{ secrets.MAILGUN_API_KEY }}
      #     domain: ${{ secrets.MAILGUN_DOMAIN }}
      #     to: ${{ secrets.TO }}
      #     subject: 'Weekly Maintenance Completed'
      #     body: |
      #       <p>The weekly maintenance task has been completed successfully.
      #       Here's a summary of the task:
      #       - Performing weekly task...
      #       - This is a fake task, just echoing some messages.
      #       - Task completed successfully.
      #       </p>
      - name: Send email
        uses: maful/github-actions-mailgun@main
        with:
          api_key: ${{ secrets.MAILGUN_API_KEY }}
          domain: ${{ secrets.MAILGUN_DOMAIN }}
          from: ${{ secrets.FROM }}
          to: ${{ secrets.TO }}
          subject: 'Weekly Maintenance Completed'
          body: |
            <p>The weekly maintenance task has been completed successfully.
            Here's a summary of the task:
            - Performing weekly task...
            - This is a fake task, just echoing some messages.
            - Task completed successfully.
            </p>

